services:
  - type: static
    name: wordle-game
    buildCommand: npm install && npm run build
    publishDir: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.0.0 